### ISSUE TITLE
Fails to load GDAL's raster GPKGs

### ISSUE THREAD

**Issue by fnorf** [ngageoint/geopackage-mapcache-android#23]
`gdal_translate -of GPKG ERDC_Whitehorse_GeoPackage.gpkg ERDC_Whitehorse_GeoPackage.gdal.gpkg`

If I try to open the resulting file on my phone, mapcache shortly pauses/freezes, then I get a popup with the following error message:

> GeoPackage Errors
> ERDC_Whitehorse_GeoPackage.gdal
> Errors:
> 
> near ".": syntax error (code 1): ,while compiling: PRAGMA table_info(ERDC_Whitehorse_GeoPackage.gdal)

**Comment by fnorf** [comment]
Poking in the dark I dropped all triggers and all new tables from GDAL's version, still got the same error.

**Comment by bosborn** [comment]
It looks like using a . in the name might be creating an invalid sqlite table name "ERDC_Whitehorse_GeoPackage.gdal".

Can you try something like:

`gdal_translate -of GPKG ERDC_Whitehorse_GeoPackage.gpkg Whitehorse_gdal.gpkg`

**Comment by fnorf** [comment]
Ah, that will be it! You need to quote those table names. A point in the name might be silly and misleading but valid. :)

I guess this is the offending line:
https://github.com/ngageoint/geopackage-android/search?utf8=%E2%9C%93&q=table_info

In these too I'd say, did not look further:
https://github.com/ngageoint/geopackage-java/search?utf8=%E2%9C%93&q=table_info
https://github.com/ngageoint/geopackage-core-java/search?utf8=%E2%9C%93&q=table_info

**Comment by bosborn** [comment]
Thanks.  It will be more cases than just the pragmas.  From a quick test queries that use the table names in the statements as well.  I'll go through and try to find all cases when I get the chance.  Until then if you can avoid .'s, things should work.

**Comment by bosborn** [comment]
The changes are on the develop branch of [geopackage-android](https://github.com/ngageoint/geopackage-android/tree/develop), [geopackage-core-java](https://github.com/ngageoint/geopackage-core-java/tree/develop), and [geopackage-java](https://github.com/ngageoint/geopackage-java/tree/develop).  They will go out with the next release.

**Comment by bosborn** [comment]
Quotation fixes for this project were released as part of:
* [geopackage-mapcache-android 1.13](https://github.com/ngageoint/geopackage-mapcache-android/releases/tag/1.13)
* [geopackage-android-map 1.3.1](https://github.com/ngageoint/geopackage-android-map/releases/tag/1.3.1)
* [geopackage-android 1.3.1](https://github.com/ngageoint/geopackage-android/releases/tag/1.3.1)
* [geopackage-core-java 1.2.1](https://github.com/ngageoint/geopackage-core-java/releases/tag/1.2.1)

Also fixed in [geopackage-java 1.2.1](https://github.com/ngageoint/geopackage-java/releases/tag/1.2.1)
